template_path: db.yaml

parameters:
  ProjectName: '{{ var.ProjectName }}'
  Environment: '{{ var.ProdEnvName }}'

  VpcId: !stack_output network/vpc.yaml::VpcId
  PrivateSubnets: !stack_output network/vpc.yaml::PrivateSubnets
  PrivateSubnetsCidr: '{{ var.PrivateSubnetsCidr }}'
  PublicSubnets: !stack_output network/vpc.yaml::PublicSubnets
  ECSClusterArn: !stack_output prod/ecs.yaml::ECSClusterArn
  ECSExecutionRoleArn: !stack_output prod/ecs.yaml::ECSExecutionRoleArn
  EC2CapacityProviderName: !stack_output prod/ecs.yaml::EC2CapacityProviderName
  PrivateDnsNamespaceArn: !stack_output network/vpc.yaml::PrivateDnsNamespaceArn
  ECRRepoArn: !stack_output common/ecr.yaml::ECRRepoArn
  SecretArn: !stack_output common/secret.yaml::SecretArn

stack_tags:
  project-name: '{{ var.ProjectName }}'
  environment: '{{ var.ProdEnvName }}'
