template_path: redis.yaml

parameters:
  ProjectName: '{{ var.ProjectName }}'
  Environment: '{{ var.ProdEnvName }}'
  EnvironmentFullName: '{{ var.ProdEnvFullName }}'

  VpcId: !stack_output network/vpc.yaml::VpcId
  PrivateSubnets: !stack_output network/vpc.yaml::PrivateSubnets
  PrivateSubnetsCidr: '{{ var.PrivateSubnetsCidr }}'
  ECSClusterArn: !stack_output prod/ecs.yaml::ECSClusterArn
  ECSExecutionRoleArn: !stack_output prod/ecs.yaml::ECSExecutionRoleArn
  EC2CapacityProviderName: !stack_output prod/ecs.yaml::EC2CapacityProviderName
  ALBTargetGroupArn: !stack_output prod/alb.yaml::ALBTargetGroupArn
  ALBSecurityGroupId: !stack_output prod/alb.yaml::ALBSecurityGroupId
  PrivateDnsNamespace: !stack_output network/dns.yaml::PrivateDnsNamespace

stack_tags:
  project-name: '{{ var.ProjectName }}'
  environment: '{{ var.ProdEnvName }}'
