template_path: web.yaml

parameters:
  ProjectName: '{{ var.ProjectName }}'
  Environment: '{{ var.ProdEnvName }}'

  VpcId: !stack_output network/vpc.yaml::VpcId
  PrivateSubnets: !stack_output network/vpc.yaml::PrivateSubnets
  PublicSubnets: !stack_output network/vpc.yaml::PublicSubnets
  ECSClusterArn: !stack_output prod/ecs.yaml::ECSClusterArn
  ECSExecutionRoleArn: !stack_output prod/ecs.yaml::ECSExecutionRoleArn
  EC2CapacityProviderName: !stack_output prod/ecs.yaml::EC2CapacityProviderName
  ECRRepoUrl: !stack_output common/ecr.yaml::ECRRepoUrl
  SecretArn: !stack_output common/secret.yaml::SecretArn
  RDSInstanceEndpoint: !stack_output prod/rds.yaml::RDSInstanceEndpoint

stack_tags:
  project-name: '{{ var.ProjectName }}'
  environment: '{{ var.ProdEnvName }}'
