FROM ruby:2.7.2-alpine AS builder

ARG BUILD_PACKAGES="build-base curl-dev git curl bash"
ARG DEV_PACKAGES="postgresql-dev nodejs yarn"
ARG RUBY_PACKAGES="tzdata"

ENV RAILS_ROOT=/app
ENV BUNDLE_PATH=$RAILS_ROOT/bundle
ENV GEM_PATH=$RAILS_ROOT
ENV GEM_HOME=$RAILS_ROOT

WORKDIR $RAILS_ROOT

RUN apk update \
        && apk upgrade \
        && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES

COPY Gemfile* package.json /app/

RUN gem update --system
RUN gem install bundler
RUN bundle config --global frozen 1 \
    && bundle install -j4 --retry 3

RUN bundle exec rails webpacker:install
RUN yarn install --production

COPY . ./

RUN bundle package
RUN bundle exec rake assets:precompile

#Remove unneeded files (cached *.gem, *.o, *.c)
RUN rm -rf $GEM_PATH/cache/*.gem ./node_modules ./tmp/cache ./vendor/cache ./spec \
    && find $GEM_PATH/gems/ -name "*.c" -delete \
    && find $GEM_PATH/gems/ -name "*.o" -delete
RUN rm -rf ./node_modules tmp/cache ./vendor/cache spec

FROM ruby:2.7.2-alpine
ARG PACKAGES="tzdata postgresql-dev nodejs bash"

ENV RAILS_ROOT=/app
ENV BUNDLE_PATH=$RAILS_ROOT/bundle
ENV GEM_PATH=$RAILS_ROOT
ENV GEM_HOME=$RAILS_ROOT

WORKDIR $RAILS_ROOT

RUN apk update \
        && apk upgrade \
        && apk add --update --no-cache $PACKAGES

COPY --from=builder $RAILS_ROOT $RAILS_ROOT

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
EXPOSE 80

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]