AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "description": "Expire old images",
              "rulePriority": 1,
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 5
              },
              "action": { 
                "type": "expire" 
              }
            }]
          }
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - ecr:GetAuthorizationToken
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      Tags:
        - Key: project-name
          Value: !Ref ProjectName

Outputs:
  ECRRepoUrl:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}"