AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-secret'
      Tags:
        - Key: project-name
          Value: !Ref ProjectName

Outputs:
  SecretArn:
    Value: !Ref Secret