ProjectName: "samaritan"
RegionFullName: "us-east-2"
RegionShortName: "use2"

StagingProjectDNSName: "staging.thepondproject.org"
ProdProjectDNSName: "thepondproject.org"

GitHubOwner: "The-Pond-Project"
GitHubRepo: "samaritan"
GitHubBranch: "aws-deploy"

StagingEnvName: "staging"
StagingEnvFullName: "staging"

ProdEnvName: "prod"
ProdEnvFullName: "production"

VpcCidr: "10.0.0.0/16"
PrivateSubnetACidr: "10.0.1.0/24"
PrivateSubnetBCidr: "10.0.2.0/24"
PublicSubnetACidr: "10.0.16.0/24"
PublicSubnetBCidr: "10.0.17.0/24"

PrivateSubnetsCidr: "10.0.0.0/20"
PublicSubnetsCidr: "10.0.16.0/20"