# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/pond_batch_records', type: :request do
  # PondBatchRecord. As you add validations to PondBatchRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      PondBatchRecord.create! valid_attributes
      get pond_batch_records_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      pond_batch_record = PondBatchRecord.create! valid_attributes
      get pond_batch_record_url(pond_batch_record)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_pond_batch_record_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      pond_batch_record = PondBatchRecord.create! valid_attributes
      get edit_pond_batch_record_url(pond_batch_record)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new PondBatchRecord' do
        expect do
          post pond_batch_records_url, params: { pond_batch_record: valid_attributes }
        end.to change { PondBatchRecord.count }.by(1)
      end

      it 'redirects to the created pond_batch_record' do
        post pond_batch_records_url, params: { pond_batch_record: valid_attributes }
        expect(response).to redirect_to(pond_batch_record_url(PondBatchRecord.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new PondBatchRecord' do
        expect do
          post pond_batch_records_url, params: { pond_batch_record: invalid_attributes }
        end.to change { PondBatchRecord.count }.by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pond_batch_records_url, params: { pond_batch_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested pond_batch_record' do
        pond_batch_record = PondBatchRecord.create! valid_attributes
        patch pond_batch_record_url(pond_batch_record),
              params: { pond_batch_record: new_attributes }
        pond_batch_record.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pond_batch_record' do
        pond_batch_record = PondBatchRecord.create! valid_attributes
        patch pond_batch_record_url(pond_batch_record),
              params: { pond_batch_record: new_attributes }
        pond_batch_record.reload
        expect(response).to redirect_to(pond_batch_record_url(pond_batch_record))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pond_batch_record = PondBatchRecord.create! valid_attributes
        patch pond_batch_record_url(pond_batch_record),
              params: { pond_batch_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested pond_batch_record' do
      pond_batch_record = PondBatchRecord.create! valid_attributes
      expect do
        delete pond_batch_record_url(pond_batch_record)
      end.to change { PondBatchRecord.count }.by(-1)
    end

    it 'redirects to the pond_batch_records list' do
      pond_batch_record = PondBatchRecord.create! valid_attributes
      delete pond_batch_record_url(pond_batch_record)
      expect(response).to redirect_to(pond_batch_records_url)
    end
  end
end
