template_path: cicd/pipeline.yaml

parameters:
  ProjectName: '{{ var.ProjectName }}'
  RegionShortName: '{{ var.RegionShortName }}'
  GitHubOwner: '{{ var.GitHubOwner }}'
  GitHubRepo: '{{ var.GitHubRepo }}'
  GitHubBranch: '{{ var.GitHubBranch }}'

stack_tags:
  project-name: '{{ var.ProjectName }}'
