development:
  adapter: async

test:
  adapter: test

staging:
  adapter: redis
  url: <%= "#{ENV.fetch('REDIS_HOST')}:#{ENV.fetch('REDIS_PORT')}" %>
  channel_prefix: the_pond_project_staging

production:
  adapter: redis
  url: <%= "#{ENV.fetch('REDIS_HOST')}:#{ENV.fetch('REDIS_PORT')}" %>
  channel_prefix: the_pond_project_production
