name: "ThePondProject CI"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: 2.7.2
      - name: Setup database
        env:
          PG_USER: postgres
          PG_PASSWORD: postgres
          RAILS_ENV: test
        run: | 
          bundle exec rails db:drop RAILS_ENV=test
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:schema:load
      - name: Setup Webpacker
        env:
          PG_USER: postgres
          PG_PASSWORD: postgres
          RAILS_ENV: test
        run: | 
          bundle exec rails webpacker:install
          yarn install
      - name: Setup Redis
        run: |
          sudo apt-add-repository ppa:redislabs/redis
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install redis-server
          sudo service redis-server start
      # Tests
      - name: Run unit tests
        run: bundle exec rspec
      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: 2.7.2
      - name: Rubocop
        run: bundle exec rubocop --parallel

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: 2.7.2
      # - name: Security audit dependencies
      #   run: bundle exec bundle audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2