template_path: redis.yaml

parameters:
  ProjectName: '{{ var.ProjectName }}'
  Environment: '{{ var.StagingEnvName }}'
  EnvironmentFullName: '{{ var.StagingEnvFullName }}'

  VpcId: !stack_output network/vpc.yaml::VpcId
  PrivateSubnets: !stack_output network/vpc.yaml::PrivateSubnets
  PrivateSubnetsCidr: '{{ var.PrivateSubnetsCidr }}'
  ECSClusterArn: !stack_output staging/ecs.yaml::ECSClusterArn
  ECSExecutionRoleArn: !stack_output staging/ecs.yaml::ECSExecutionRoleArn
  ALBTargetGroupArn: !stack_output staging/alb.yaml::ALBTargetGroupArn
  ALBSecurityGroupId: !stack_output staging/alb.yaml::ALBSecurityGroupId
  PrivateDnsNamespace: !stack_output network/dns.yaml::PrivateDnsNamespace

stack_tags:
  project-name: '{{ var.ProjectName }}'
  environment: '{{ var.StagingEnvName }}'
