template_path: web.yaml

parameters:
  ProjectName: '{{ var.ProjectName }}'
  Environment: '{{ var.StagingEnvName }}'
  EnvironmentFullName: '{{ var.StagingEnvFullName }}'

  VpcId: !stack_output network/vpc.yaml::VpcId
  PrivateSubnets: !stack_output network/vpc.yaml::PrivateSubnets
  PrivateSubnetsCidr: '{{ var.PrivateSubnetsCidr }}'
  ECSClusterArn: !stack_output staging/ecs.yaml::ECSClusterArn
  ECSExecutionRoleArn: !stack_output staging/ecs.yaml::ECSExecutionRoleArn
  ECRRepoUrl: !stack_output common/ecr.yaml::ECRRepoUrl
  SecretArn: !stack_output common/secret.yaml::SecretArn
  DBHost: !stack_output staging/ecs.yaml::ECSInstancePrivateDnsName
  ALBTargetGroupArn: !stack_output staging/alb.yaml::ALBTargetGroupArn
  ALBSecurityGroupId: !stack_output staging/alb.yaml::ALBSecurityGroupId

stack_tags:
  project-name: '{{ var.ProjectName }}'
  environment: '{{ var.StagingEnvName }}'
