AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  EnvironmentFullName:
    Type: String

  VpcId:
    Type: String
  PrivateSubnets:
    Type: String
  PrivateSubnetsCidr:
    Type: String
  ECSClusterArn:
    Type: String
  ECSExecutionRoleArn:
    Type: String
  EC2CapacityProviderName:
    Type: String
    Default: ''
  ECRRepoUrl:
    Type: String
  SecretArn:
    Type: String
  DBHost:
    Type: String
  ALBTargetGroupArn:
    Type: String
  ALBSecurityGroupId:
    Type: String
  CDNUri:
    Type: String
    Default: ''
  PrivateDnsNamespace:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']
  IsNotProd: !Not [Condition: IsProd]

Resources:
  WebTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ProjectName}-web-${Environment}
      ExecutionRoleArn: !Ref ECSExecutionRoleArn
      TaskRoleArn: !Ref WebServiceRole
      RequiresCompatibilities:
        - EC2
      NetworkMode: awsvpc
      Memory: !If [IsProd, 1024, 512]
      Cpu: !If [IsProd, 1024, 512]
      ContainerDefinitions:
        - Name: !Sub ${ProjectName}-web-${Environment}
          Image: !Sub '${ECRRepoUrl}:samaritan-latest'
          Essential: true
          PortMappings:
            - Protocol: tcp
              ContainerPort: 80
          Environment:
            - Name: RAILS_ENV
              Value: !Ref EnvironmentFullName
            - Name: RACK_ENV
              Value: !Ref EnvironmentFullName
            - Name: NODE_ENV
              Value: !Ref EnvironmentFullName
            - Name: PORT
              Value: 80
            - Name: DB_HOST
              Value: !Ref DBHost
            - Name: CDN_HOST
              Value: !Ref CDNUri
            - Name: RAILS_SERVE_STATIC_FILES
              Value: true
            - Name: REDIS_PORT
              Value: 6379
            - Name: REDIS_DB
              Value: 0
            - Name: REDIS_HOST
              Value: !Sub 'redis-${Environment}.${PrivateDnsNamespace}'
          Secrets:
            - Name: SECRET_KEY_BASE
              ValueFrom: !Sub '${SecretArn}:secretKey::'
            - Name: DB_USERNAME
              ValueFrom: !Sub '${SecretArn}:dbUsername::'
            - Name: DB_PASSWORD
              ValueFrom: !Sub '${SecretArn}:dbPassword::'
            - Name: TWILIO_ACCOUNT_SID
              ValueFrom: !Sub '${SecretArn}:twilioAccountSID::'
            - Name: TWILIO_AUTH_TOKEN
              ValueFrom: !Sub '${SecretArn}:twilioAuthToken::'
            - Name: TWILIO_PHONE_NUMBER
              ValueFrom: !Sub '${SecretArn}:twilioPhoneNumber::'
            - Name: STRIPE_PUBLISHABLE_KEY
              ValueFrom: !Sub '${SecretArn}:stripePublishableKey::'
            - Name: STRIPE_SECRET_KEY
              ValueFrom: !Sub '${SecretArn}:stripeSecretKey::'
            - Name: STRIPE_SIGNING_SECRET
              ValueFrom: !Sub '${SecretArn}:stripeSigningSecret::'
            - Name: GOOGLE_MAPS_API_KEY
              ValueFrom: !Sub '${SecretArn}:googleMapsApiKey::'
            - Name: SUDO_PASSWORD
              ValueFrom: !Sub '${SecretArn}:sudoPassword::'
            - Name: INTERNAL_API_KEY
              ValueFrom: !Sub '${SecretArn}:internalApiKey::'
            - Name: SAMARITAN_CLIENT_TOKEN
              ValueFrom: !Sub '${SecretArn}:samaritanClientToken::'
            - Name: REDIS_URL
              ValueFrom: !Sub '${SecretArn}:redisUrl::'
            - Name: GEOLOCATION_API_KEY
              ValueFrom: !Sub '${SecretArn}:geolocationApiKey::'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${ProjectName}-web-${Environment}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Tags:
        - Key: project-name
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

  WebLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${ProjectName}-web-${Environment}
      RetentionInDays: 30

  WebServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-web-${Environment}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: WebServiceRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - rds:*
      Tags:
        - Key: project-name
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

  WebService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSClusterArn
      DesiredCount: !If [IsProd, 2, 1]
      DeploymentConfiguration:
        MinimumHealthyPercent: !If [IsProd, 50, 0]
      LoadBalancers:
        - TargetGroupArn: !Ref ALBTargetGroupArn
          ContainerName: !Sub ${ProjectName}-web-${Environment}
          ContainerPort: 80
      CapacityProviderStrategy:
        - !If
          - IsProd
          - CapacityProvider: !Ref EC2CapacityProviderName
            Weight: 1
          - !Ref AWS::NoValue
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !GetAtt WebSecurityGroup.GroupId
          Subnets: !Split [ ',', !Ref PrivateSubnets ]
      TaskDefinition: !Ref WebTaskDefinition
      Tags:
        - Key: project-name
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ProjectName}-web-${Environment}
      GroupDescription: Security group for web app
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref ALBSecurityGroupId
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - SourceSecurityGroupId: !Ref ALBSecurityGroupId
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        - !If
          - IsNotProd
          - CidrIp: !Ref PrivateSubnetsCidr
            IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
          - !Ref AWS::NoValue
      Tags:
        - Key: project-name
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment